//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObservaTerra.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.ContainedAreas = new HashSet<Area>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int AreaId { get; set; }
    
        public virtual ICollection<Area> ContainedAreas { get; set; }
        public virtual Area ContainerArea { get; set; }
        public virtual Indicator Indicator { get; set; }
    }
}
