//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObservaTerra.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicator
    {
        public Indicator()
        {
            this.Observations = new HashSet<Observation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Measure Measure { get; set; }
        public virtual ICollection<Observation> Observations { get; set; }
        public virtual ITime ITime { get; set; }
    }
}
