//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObservaTerra.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Observation
    {
        public Observation()
        {
            this.IComponents = new HashSet<IComponent>();
        }
    
        public int Id { get; set; }
        public System.TimeSpan CreationDate { get; set; }
    
        public virtual Indicator Indicator { get; set; }
        public virtual User UserAuthor { get; set; }
        public virtual Organization SourceOrganization { get; set; }
        public virtual ICollection<IComponent> IComponents { get; set; }
    }
}
