//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObservaTerra.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Observation
    {
        public Observation()
        {
            this.IComponents = new HashSet<IComponent>();
        }
    
        public int Id { get; set; }
    
        public virtual Indicator Indicator { get; set; }
        public virtual User UserAuthor { get; set; }
        public virtual Organization SourceOrganization { get; set; }
        public virtual ICollection<IComponent> IComponents { get; set; }
    }
}
