//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObservaTerra.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Observations = new HashSet<Observation>();
            this.Organizations = new HashSet<Organization>();
            this.Roles = new HashSet<Role>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Observation> Observations { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
